site_name: lenaleto24
site_description: Портфолио # Описание сайта, добавляется в meta-теги
theme: # Тема сайта, информация о ее параметрах
  name: material # Название темы
  logo: images/logo.png # Ссылка на логотип сайта, логотип добавляется в папку `docs/images`
  extra:
    favicon: images/logo.png
  font:
    text: Inter # Шрифт текста
    code: Fira Code # Шрифт для текста кода
  language: ru # Язык
  palette: # Настройки светлой и тёмной тем
    # Настройки светлой темы
    - scheme: default 
      toggle:
        icon: material/weather-sunny # Иконка для активации светлой темы
        name: Выключить солнышко # Всплывающий текст-подсказка
      primary: deep purple # Основной цвет
      accent: purple # Акцентный цвет
      # вы можете использовать любой цвет из списка: 
      # red; pink; purple; deep purple; indigo; blue; light blue; cyan; teal; 
      # green; light green; lime; yellow; amber; orange; deep orange; brown; 
      # grey; blue grey; black; white

    # Настройки тёмной темы
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Позвать солнышко
      primary: deep purple
      accent: purple
  features: # настройки функциональностей темы
    #- navigation.sections # Добавление разделов верхнего уровня в боковом меню, отключение спойлеров в боковом меню
    - navigation.path # Хлебные крошки
    - navigation.indexes # Позволяет создавать корневые страницы разделов меню. Корневая страница должна лежать в папке раздела и называться index.md. Пример использования корневых страниц приведен ниже в настройках nav
    #- navigation.tabs # Верхнее меню
    - navigation.tabs.sticky # Фиксация верхнего меню
    #- navigation.expand # Разворачивает спойлеры в левом меню по умолчанию
    - navigation.expand: false
    - navigation.tracking
    - toc.integrate # Фиксирует оглавление страницы в левом меню
    - navigation.instant # Функция быстрой загрузки страниц
    - navigation.top # Добавляет кнопку «к началу» для быстрой обратной прокрутки страницы
    - search.suggest # Подсказки при вводе поискового запроса
    - search.highlight # Подсветка результатов поиска в тексте страницы
    - content.code.copy # Кнопка копирования в блоке кода

nav: # Структура сайта
- Главная страница: index.md
- Гайды Telegram: 
  - Отправить отложенное сообщение: instruction1.md
  - Закрепить сообщение в чате: instruction2.md

markdown_extensions: # Расширения markdown
  - admonition # Поддержка информационных панелей (сообщений типа «Внимание», «Совет», «Примечание», etc.)
  - footnotes # Поддержка встроенных сносок на страницах
  - attr_list # Использование html-атрибутов и CSS в элементах markdown
  - md_in_html # Поддержка markdown внутри html
  - def_list # Поддержка списков определений
  - pymdownx.tabbed: # Использование вкладок (табов)
      alternate_style: true
  - pymdownx.details # Использование спойлеров (катов)
  - pymdownx.highlight: # Подсветка синтаксиса в блоках кода
      anchor_linenums: true
  - pymdownx.superfences # Поддержка вложенных блоков кода
  - pymdownx.emoji: # Иконки и эмодзи
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search # Плагин для подключения поиска на портале